# Generated by Django 4.0.4 on 2022-05-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_post_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/default.png', help_text='Upload a Post image', upload_to='images/', verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
